# Generated by Django 5.2.7 on 2025-11-27 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0008_user_is_active_user_is_staff_alter_user_is_superuser'),
        ('post', '0011_comment_reply_to_username'),
        ('transaction', '0018_manualpaymentdecision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('report_type', models.CharField(blank=True, choices=[('post', 'Post'), ('connection', 'Connection'), ('transaction', 'Transaction'), ('conversation', 'Conversation'), ('message', 'Message')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('about_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_about', to=settings.AUTH_USER_MODEL)),
                ('decision_maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_decisions', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_sent', to=settings.AUTH_USER_MODEL)),
                ('reported_connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='account.connection')),
                ('reported_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='post.post')),
                ('reported_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='transaction.transaction')),
            ],
        ),
    ]
