# Generated by Django 5.2.7 on 2025-11-28 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_appeal_appealdecision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealdecision',
            name='appeal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='report.appeal'),
        ),
    ]
