# Generated by Django 5.2.7 on 2025-11-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_appealdecision_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdecision',
            name='has_appeals',
            field=models.BooleanField(default=False),
        ),
    ]
