# Generated by Django 5.2.7 on 2025-11-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_reportdecision_has_appeals'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='concluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
