# Generated by Django 5.2.7 on 2025-11-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_report_concluded_report_dismissed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdecision',
            name='from_appeal',
            field=models.BooleanField(default=False),
        ),
    ]
