# Generated by Django 5.2.7 on 2025-12-03 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0012_message_forward_count'),
        ('report', '0008_reportdecision_from_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reported_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='conversation.message'),
        ),
    ]
