"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv
from enum import Enum

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
BACKEND_URL = os.getenv("BACKEND_URL", "http://localhost:8000/")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-zf%yg+ym2h%83%jc=9pdweq)i#q1lpoz#5=82ano8gz(a5!_i^"
)
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "false") != "false"

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',')
if not ALLOWED_HOSTS:
    raise ValueError("ALLOWED_HOSTS must be set in the environment")
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "account",
    "post",
    "transaction",
    "report",
    "notification",
    "support",
    "usage",
    "conversation",
    "analytics",

    "rest_framework",
    "rest_framework_simplejwt",
    "django_filters",

    "corsheaders",
    "debug_toolbar"
]

AUTH_USER_MODEL = "account.User"
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",

]

ROOT_URLCONF = "server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "server.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DB_NAME = os.getenv("DB_NAME")
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")
if not DB_NAME:
    raise ValueError("DB_NAME must be set in the environment")
if not DB_USER:
    raise ValueError("DB_USER must be set in the environment")
if not DB_PASSWORD:
    raise ValueError("DB_PASSWORD must be set in the environment")
if not DB_HOST:
    raise ValueError("DB_HOST must be set in the environment")
if not DB_PORT:
    raise ValueError("DB_PORT must be set in the environment")
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": DB_NAME,
        "USER": DB_USER,
        "PASSWORD": DB_PASSWORD,
        "HOST": DB_HOST,
        "PORT": DB_PORT,
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated"
    ]
}
INTERNAL_IPS = [
    "127.0.0.1",
]
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST_USER = os.getenv('GMAIL_ACCOUNT')
EMAIL_HOST_PASSWORD = os.getenv('GMAIL_APP_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
if not CORS_ALLOWED_ORIGINS:
    raise ValueError("CORS_ALLOWED_ORIGINS must be set in the environment")
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
if not CSRF_TRUSTED_ORIGINS or CSRF_TRUSTED_ORIGINS == [""]:
    raise ValueError("CSRF_TRUSTED_ORIGINS is not set or empty")

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
POLAR_ACCESS_TOKEN = os.getenv('POLAR_ACCESS_TOKEN')
POLAR_SERVER = os.getenv('POLAR_SERVER')
if not POLAR_ACCESS_TOKEN or not POLAR_SERVER:
    raise ValueError("POLAR_ACCESS_TOKEN and POLAR_SERVER must be set in the environment")
SIGNUP_FREE_CONNECTS = int(os.getenv('SIGNUP_FREE_CONNECTS', 5))
MONTHLY_FREE_CONNECTS = int(os.getenv('MONTHLY_FREE_CONNECTS', 5))
CONNECTS_PRODUCT_ID_5_CONNECTS = os.getenv('CONNECTS_PRODUCT_ID_5_CONNECTS')
CONNECTS_PRODUCT_ID_20_CONNECTS = os.getenv('CONNECTS_PRODUCT_ID_20_CONNECTS')
CONNECTS_PRODUCT_ID_100_CONNECTS = os.getenv('CONNECTS_PRODUCT_ID_100_CONNECTS')
CONNECTS_PRODUCT_ID_10_SUBS = os.getenv('CONNECTS_PRODUCT_ID_10_SUBS')
POLAR_ORDER_PAID_WEBHOOK_SECRET = os.getenv('POLAR_ORDER_PAID_WEBHOOK_SECRET', '')
POLAR_ORDER_OPTIONS={
    "C5": {
        "product_id": CONNECTS_PRODUCT_ID_5_CONNECTS,
        "connects": 5,
        "price": 5,
        "is_sub": False
    },
    "C20": {
        "product_id": CONNECTS_PRODUCT_ID_20_CONNECTS,
        "connects": 20,
        "price": 20,
        "is_sub": False
    },
    "C100": {
        "product_id": CONNECTS_PRODUCT_ID_100_CONNECTS,
        "connects": 100,
        "price": 100,
        "is_sub": False
    },
    "S10": {
        "product_id": CONNECTS_PRODUCT_ID_10_SUBS,
        "connects": 20,
        "price": 10,
        "is_sub": True
    }
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),   # make access token last 1 hour
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365),  # make refresh token last 7 days
    'ROTATE_REFRESH_TOKENS': True
}

class POST_ACTIVITY_TYPES(Enum):
    VIEW_POST = "view"
    LIKE_POST = "like"
    COMMENT_POST = "comment"
    LIKE_COMMENT = "like_comment"
    REPLY_COMMENT = "reply"
    SEND_POST = "send"
    SAVE_POST = "save"


POST_ACTIVITY_WEIGHTS = {
    POST_ACTIVITY_TYPES.VIEW_POST: 1,
    POST_ACTIVITY_TYPES.LIKE_COMMENT: 10,
    POST_ACTIVITY_TYPES.LIKE_POST: 15,
    POST_ACTIVITY_TYPES.REPLY_COMMENT: 20,
    POST_ACTIVITY_TYPES.COMMENT_POST: 30,
    POST_ACTIVITY_TYPES.SAVE_POST: 45,
    POST_ACTIVITY_TYPES.SEND_POST: 60,
}

TOP_K_INTERESTS = 5
TOP_K_INTERESTS_POST_RETURNED_COUNT = [5, 4, 3, 2, 1]
TOP_POSTS_RECOMMENDED_COUNT = 20
COSINE_THRESHOLD = 0.3
START_RECOMMENDATION_AT_POST_COUNT = 1000

EMBEDDING_MODEL_NAME = "gemini-embedding-001"


ALLOWED_CONTENT_TYPES = ["image/jpeg", "image/png"]
ALLOWED_EXTENSIONS = [".jpg", ".jpeg", ".png"]
MAX_FILE_SIZE_MB = 20