# Generated by Django 5.2.7 on 2025-11-30 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0018_manualpaymentdecision'),
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectusage',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.transaction'),
        ),
    ]
