# Generated by Django 5.2.7 on 2026-02-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.BigIntegerField(default=0),
        ),
    ]
