# Generated by Django 5.2.7 on 2025-12-05 10:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_previousrecommendedpost_userinterest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='previousrecommendedpost',
            unique_together={('post', 'user')},
        ),
    ]
