# Generated by Django 5.2.7 on 2025-10-28 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_paymentinfo_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info_list', to='post.post'),
        ),
    ]
