# Generated by Django 5.2.7 on 2025-12-05 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_previousrecommendedpost_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroidMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=1)),
                ('centroid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.userinterest')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
    ]
