# Generated by Django 5.2.7 on 2025-12-05 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_centroidmember'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CentroidMember',
            new_name='ClusterMember',
        ),
    ]
