# Generated by Django 5.2.7 on 2025-10-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_comment_commented_by_alter_comment_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='likecomment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='save',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
