# Generated by Django 5.2.7 on 2025-12-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_rename_centroidmember_clustermember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.CharField(max_length=8000),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=63206),
        ),
    ]
