# Generated by Django 5.2.7 on 2025-10-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_like_active_likecomment_active_paymentinfo_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saves',
            field=models.IntegerField(default=0),
        ),
    ]
