# Generated by Django 5.2.7 on 2025-11-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_to_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
