# Generated by Django 5.2.7 on 2025-11-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_comment_reply_to_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
