# Generated by Django 5.2.7 on 2025-12-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_post_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='forwards',
            field=models.IntegerField(default=0),
        ),
    ]
