# Generated by Django 5.2.7 on 2025-12-04 22:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_enable_pgvector'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('connects', models.PositiveIntegerField(default=0)),
                ('connections', models.PositiveIntegerField(default=0)),
                ('connection_requests', models.PositiveIntegerField(default=0)),
                ('email_verified', models.BooleanField(default=False)),
                ('otp_secret', models.CharField(blank=True, max_length=32, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('post_likes', models.IntegerField(default=0)),
                ('connects_needed_for_connection', models.PositiveIntegerField(default=1)),
                ('last_month_free_connects_date', models.DateTimeField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported', models.BooleanField(default=False)),
                ('removed', models.BooleanField(default=False)),
                ('banned', models.BooleanField(default=False)),
                ('connectSpent', models.IntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('reconnection_requested', models.BooleanField(default=False)),
                ('reconnection_count', models.IntegerField(default=0)),
                ('reconnection_rejected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_users', to=settings.AUTH_USER_MODEL)),
                ('initiating_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_list', to=settings.AUTH_USER_MODEL)),
                ('reconnection_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconnection_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
