# Generated by Django 5.2.7 on 2025-10-28 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='reconnection_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connection',
            name='reconnection_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconnection_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='connection_requests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='connections',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='connection',
            name='iniating_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
