# Generated by Django 5.2.7 on 2025-10-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_connection_message_connection_reconnection_requested_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='reconnection_count',
            field=models.IntegerField(default=0),
        ),
    ]
