# Generated by Django 5.2.7 on 2025-10-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_connection_reconnection_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='reconnection_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
