# Generated by Django 5.2.7 on 2025-11-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_is_active_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='iniating_user',
            new_name='initiating_user',
        ),
        migrations.AddField(
            model_name='connection',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
