# Generated by Django 5.2.7 on 2025-11-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_rename_iniating_user_connection_initiating_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='connects_needed_for_connection',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
