# Generated by Django 5.2.7 on 2025-11-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_otp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_month_free_connects_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
