# Generated by Django 5.2.7 on 2025-12-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_user_last_month_free_connects_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='post_likes',
            field=models.IntegerField(default=0),
        ),
    ]
