# Generated by Django 5.2.7 on 2025-11-27 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='message',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
    ]
