# Generated by Django 5.2.7 on 2025-11-27 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_user'),
        ('report', '0002_remove_report_decision_maker_reportdecision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='report',
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='report_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='report.reportdecision'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
