# Generated by Django 5.2.7 on 2025-12-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0004_alter_conversation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='category',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('requests', 'Requests'), ('archived', 'Archived')], default='primary', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ConversationCategory',
        ),
    ]
