# Generated by Django 5.2.7 on 2025-12-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0005_member_category_delete_conversationcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='conversation_logos/'),
        ),
    ]
