# Generated by Django 5.2.7 on 2025-12-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0009_message_forwarded_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
