# Generated by Django 5.2.7 on 2025-12-03 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0010_alter_message_message'),
        ('post', '0013_post_forwards'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_conversations', to='post.post'),
        ),
    ]
