# Generated by Django 5.2.7 on 2025-12-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0011_message_shared_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='forward_count',
            field=models.IntegerField(default=0),
        ),
    ]
