# Generated by Django 5.2.7 on 2025-12-04 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_user_last_month_free_connects_date'),
        ('conversation', '0012_message_forward_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.connection'),
        ),
    ]
