# Generated by Django 5.2.7 on 2025-12-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0013_conversation_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
