# Generated by Django 5.2.7 on 2025-11-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_id', models.TextField(blank=True, null=True)),
                ('is_payment_required', models.BooleanField(default=True)),
                ('connects', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=255)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshot/')),
                ('transaction_id', models.TextField(blank=True, null=True)),
                ('product_id', models.TextField(blank=True, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
