# Generated by Django 5.2.7 on 2025-11-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transaction_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='billing_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
