# Generated by Django 5.2.7 on 2025-11-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transaction_billing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='celebrated',
            field=models.BooleanField(default=False),
        ),
    ]
