# Generated by Django 5.2.7 on 2025-11-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_subscription_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='product_code_internal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='product_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
