# Generated by Django 5.2.7 on 2025-11-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_subscription_product_code_internal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='product_code_internal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
