# Generated by Django 5.2.7 on 2025-11-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_transaction_product_code_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='product_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
