# Generated by Django 5.2.7 on 2025-11-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_subscription_product_name_transaction_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='recurring_interval',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='recurring_interval_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
