# Generated by Django 5.2.7 on 2025-11-27 14:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_manualpaymentoptions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManualPaymentOptions',
            new_name='ManualPaymentOption',
        ),
    ]
