# Generated by Django 5.2.7 on 2025-11-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_rename_manualpaymentoptions_manualpaymentoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualpaymentoption',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='manual_payment_option/logo/'),
        ),
    ]
