# Generated by Django 5.2.7 on 2025-11-27 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0015_manualpaymentoption_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='manual_payment_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.manualpaymentoption'),
        ),
    ]
