# Generated by Django 5.2.7 on 2025-11-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0016_transaction_manual_payment_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
